name: Pull Request Opened

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.3"

      - name: Install PHP dependencies
        run: composer install --no-interaction --prefer-dist --no-suggest

      - name: Install NodeJS dependencies
        run: npm install

      - name: Build assets
        run: npm run build

      - name: Run tests
        run: php artisan test

      - name: Bundle
        run: |
          chmod +x bundle.sh
          ./bundle.sh
        shell: bash

      - name: Upload artifact to server
        run: |
          touch key
          chmod 600 key
          echo "${{ secrets.DEPLOYKEY }}" >> key
          mkdir -p $HOME/.ssh
          ssh-keyscan -H ${{ secrets.HOST }} >> $HOME/.ssh/known_hosts
          scp -i key -o UserKnownHostsFile=$HOME/.ssh/known_hosts app.zip ${{ secrets.USERNAME }}@${{ secrets.HOST }}:/opt/bitnami/nginx/html/laravel/app.zip
          rm key
        shell: bash

      - name: Deploy
        run: |
          touch key
          chmod 600 key
          echo "${{ secrets.DEPLOYKEY }}" >> key
          mkdir -p $HOME/.ssh
          ssh-keyscan -H ${{ secrets.HOST }} >> $HOME/.ssh/known_hosts
          chmod +x deploy.sh
          ./deploy.sh ${{ secrets.USERNAME }} ${{ secrets.HOST }} key
          ssh -i key ${{ secrets.USERNAME }}@${{ secrets.HOST }} "cd /opt/bitnami/nginx/html/laravel && ./update.sh"
          rm key
        shell: bash

      - name: Upload artifact to GitHub
        uses: actions/upload-artifact@v2
        with:
          name: build
          path: app.zip
