name: Prettier Lint

on:
    pull_request:
        branches:
            - main
        types:
            - opened
            - synchronize
            - reopened
        paths:
            - '*.json'
            - '*.yml'
            - '*.yaml'
            - '*.js'
            - '*.md'
            - '*.html'
            - '*.css'

concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true

jobs:
    lint:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Setup NodeJS
              uses: ./.github/actions/setup-nodejs

            - name: Lint JS
              run: npm run lint
