name: Prerelease

on:
    release:
        types: [prereleased]

concurrency:
    group: 'prerelease'
    cancel-in-progress: true

jobs:
    release:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Setup Node.js
              uses: ./.github/actions/setup-nodejs

            - name: Check NPM Dependencies
              run: npm audit

            - name: Setup PHP
              uses: ./.github/actions/setup-php

            - name: Check PHP Dependencies
              run: composer audit

            - name: Bundle
              run: |
                  chmod +x bundle.sh
                  ./bundle.sh
              shell: bash
