name: Test PHP

on:
    pull_request:
        branches:
            - main
        types:
            - opened
            - synchronize
            - reopened
        paths:
            - '**/*.php'
            - 'tests/**/*'
            - 'phpunit.xml'
            - 'composer.json'
            - 'composer.lock'
            - '.github/workflows/test-php.yml'
            - '.github/actions/setup-php/action.yml'
    workflow_dispatch:

concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true

jobs:
    lint:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Setup NodeJS
              uses: ./.github/actions/setup-nodejs

            - name: Setup PHP
              uses: ./.github/actions/setup-php

            - name: Test PHP
              run: |
                  npm run build
                  composer run test
